/*
31-Jan-2023
what is rendering ?
d/b static and dynamic?
d/b
where is edge functions hosted?

01-Feb-2023
Ye chackar sir se puxhna hy cause .tsx component mush return jsx
and async function always return a Promise but Next JS wale website per kha
rahe hyn server components per direct async await supported hy


16-Feb-2023
getStaticProps() se data build time per generate hota hy [one time]
request time per data fetch karna hy with getServerSideProps()

























*/